version: '3.8'

services:
  app:
    build:
      args:
        USERNAME: node
        # Update 'VARIANT' to pick a Node version: 18, 16, 14.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local on arm64/Apple Silicon.
        VARIANT: 16-bullseye
    env_file: ../.env
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
      - bash_history:/commandhistory
      - node_modules:/workspace/node_modules
      - pnpm_store:/home/node/.local/share/pnpm/store
      - vscode_extensions:/home/node/.vscode-server/extensions

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    env_file: ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../config/docker/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6-alpine
    restart: always
    env_file: ../.env
    command: /bin/sh -c "redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data

volumes:
  bash_history:
  node_modules:
  pnpm_store:
  postgres_data:
  redis_data:
  vscode_extensions:
