version: '3.9'

services:
  app:
    build:
      args:
        USERNAME: node
        # Update 'VARIANT' to pick a Node version: 18, 16, 14.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local on arm64/Apple Silicon.
        VARIANT: 16-bullseye
    env_file: ../.env
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
      - bash_history:/commandhistory
      - node_modules:/workspace/node_modules
      - pnpm_store:/home/node/.local/share/pnpm/store
      - vscode_extensions:/home/node/.vscode-server/extensions
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:14.5-alpine
    restart: unless-stopped
    env_file: ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../config/docker/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 54320:5432
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2-alpine
    restart: always
    env_file: ../.env
    command: /bin/sh -c "redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    ports:
      - 63790:6379
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  bash_history:
  node_modules:
  pnpm_store:
  postgres_data:
  redis_data:
  vscode_extensions:
