openapi: 3.0.2

info:
  title: API Title
  version: 0.0.1

servers:
  - url: http://localhost:3333

paths:
  /api/users:
    get:
      tags:
        - users
      summary: List users
      description: Show user list paginated
      parameters:
        - name: page
          in: query
          explode: false
          required: false
          schema:
            type: integer
            format: int64
            default: 1
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    $ref: ./openapi/schemas/pagination.yml
                  data:
                    type: array
                    items:
                      $ref: ./openapi/schemas/user.yml
